In [2]:
#numpy-numeric python
#used for working with arrays and numeric values
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [3]:
print("np version:",np.__version__)

np version: 1.24.3


In [7]:
#arrays
import numpy as np
a=[1,2,3,4,5]
x=np.array(a)
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
a=[1,2,3,4,5]
print(a*2)
x=np.array(a)
print(x)
print(x*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1 2 3 4 5]
[ 2  4  6  8 10]


In [23]:
#methods of creating of arrays

#1-zeros array
print(np.zeros(10))

#2-array of ones
print(np.ones(10))

#3-using arrange function
print(np.arange(1,10))       
print(np.arange(1,10,2)) 
print(np.arange(50,20,-6))       

#evenly spaced values
print(np.linspace(1,10,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[50 44 38 32 26]
[ 1.    3.25  5.5   7.75 10.  ]


In [36]:
#types of array
#1D,2D,3D

#Creating 1-D array
a=[1,2,3,4,5]
x=np.array(a)
print("1D array is:",x)
print("dimention:",x.ndim)

#creating 2D array
a=[[1,2],[3,4]]
x=np.array(a)
print("2D array is:",x)
print("dimention:",x.ndim)

#creating 3D array
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array is:",a)
print("dimention:",a.ndim)

1D array is: [1 2 3 4 5]
dimention: 1
2D array is: [[1 2]
 [3 4]]
dimention: 2
3D array is: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimention: 3


In [42]:
#shape,size,dimension & data types of array
a=np.array([1,2,3,4,5,6,7,8])
print("shape:",a.shape)
print("size:",a.size)
print("dimension:",a.ndim)
print("data types of values:",a.dtype)




shape: (8,)
size: 8
dimension: 1
data types of values: int64


In [45]:
b=np.array([[1,2],[3,4]])
print("shape:",b.shape)
print("size:",b.size)
print("dimension:",b.ndim)
print("data types of values:",b.dtype)

shape: (2, 2)
size: 4
dimension: 2
data types of values: int64


In [44]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("shape:",a.shape)
print("size:",a.size)
print("dimension:",a.ndim)
print("data types of values:",a.dtype)


shape: (2, 2, 2)
size: 8
dimension: 3
data types of values: int64


In [46]:
#create 2D and 3D arrays and check all array metrics
a=np.array([[[1,2,3,4],[5,6,7,8]],
            [[10,20,30,40],[50,60,70,80]],
           [[50,51,52,53],[61,62,63,64]]])
print("shape:",a.shape)
print("size:",a.size)
print("dimension:",a.ndim)
print("data types of values:",a.dtype)

shape: (3, 2, 4)
size: 24
dimension: 3
data types of values: int64


In [49]:
#aggregate functions
a=np.array([[[1,2,3,4],[5,6,7,8]],
            [[10,20,30,40],[50,60,70,80]],
           [[50,51,52,53],[61,62,63,64]]])
print("min:",np.min(a))
print("max:",np.max(a))
print("mean:",np.mean(a))
print("median:",np.median(a))
print("sum:",np.sum(a))
print("standard deviation:",np.std(a))

min: 1
max: 80
mean: 35.5
median: 45.0
sum: 852
standard deviation: 26.301140659674818


In [14]:
#task 1,2,3,4,5
print(np.zeros(15))
print(np.ones(10))
print(np.arange(5,50,5))
print(np.arange(100,10,-10))
print(np.linspace(0,20,7))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 5 10 15 20 25 30 35 40 45]
[100  90  80  70  60  50  40  30  20]
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.        ]


In [20]:
#task 6
#shape,size,dimension & data types of array
#Creating 1-D array
a=[1,2,3,4,5]
x=np.array(a)
print("1D array is:",x)
print("dimention:",x.ndim)

#creating 2D array
a=[[1,2],[3,4]]
y=np.array(a)
print("2D array is:",y)
print("dimention:",y.ndim)

#creating 3D array
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("3D array is:",a)
print("dimention:",a.ndim)

print("shape:",x.shape)
print("size:",x.size)
print("dimension:",x.ndim)
print("data types of values:",x.dtype)

print("shape:",y.shape)
print("size:",y.size)
print("dimension:",y.ndim)
print("data types of values:",y.dtype)

print("shape:",a.shape)
print("size:",a.size)
print("dimension:",a.ndim)
print("data types of values:",a.dtype)


1D array is: [1 2 3 4 5]
dimention: 1
2D array is: [[1 2]
 [3 4]]
dimention: 2
3D array is: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
dimention: 3
shape: (5,)
size: 5
dimension: 1
data types of values: int64
shape: (2, 2)
size: 4
dimension: 2
data types of values: int64
shape: (2, 2, 2)
size: 8
dimension: 3
data types of values: int64


In [25]:
#task 7
a = np.array([12, 25, 30, 45, 50, 65, 70, 85, 90])
print("min",np.min(a))
print("max",np.max(a))
print("mean",np.mean(a))
print("median",np.median(a))
print("sum",np.sum(a))
print("std",np.std(a))

min 12
max 90
mean 52.44444444444444
median 50.0
sum 472
std 25.582594391548117


In [8]:
import numpy as np
#indexing and slicing in arrays 

#1D
a=np.array([5,6,7,8,9,7])

#indexing
print(a[1])
print(a[-4])

#slicing
print(a[:])
print(a[::2])
print(a[::-2])
print(a[2:5:3])

6
7
[5 6 7 8 9 7]
[5 7 9]
[7 8 6]
[7]


In [34]:
#2D arrays
a=np.array([[2,3,4],[3,3,5],[3,5,6]])
print(a)

#printing single elements
print(a[2,1])
print(a[0,0])
print(a[-1,-1])

#print rows
print(a[1])
print(a[-1])
print(a[0:3:2])

#print columns
print(a[:,0])
print(a[:,2])
print(a[:2,2])
print(a[::2,2])
print(a[:,:])

#print submatrix
print(a[0:2,0:2])
print(a[1:2,0:2])

[[2 3 4]
 [3 3 5]
 [3 5 6]]
5
2
6
[3 3 5]
[3 5 6]
[[2 3 4]
 [3 5 6]]
[2 3 3]
[4 5 6]
[4 5]
[4 6]
[[2 3 4]
 [3 3 5]
 [3 5 6]]
[[2 3]
 [3 3]]
[[3 3]]


In [36]:
#mathematical operation in numpy array
a=np.array([12,13,14])
b=np.array([22,33,55])
print("addition",a+b)
print("multiplication",a*b)
print("substraction",a-b)
print("division",a/b)
print("modulus",a%b)

addition [34 46 69]
multiplication [264 429 770]
substraction [-10 -20 -41]
division [0.54545455 0.39393939 0.25454545]
modulus [12 13 14]


In [39]:
#create two 2 D array and do same calculation
a=np.array([[3,34,55],[66,88,88]])
b=np.array([[99,77,88],[88,55,44]])
print("addition",a+b)
print("multiplication",a*b)
print("substraction",a-b)
print("division",a/b)
print("modulus",a%b)

addition [[102 111 143]
 [154 143 132]]
multiplication [[ 297 2618 4840]
 [5808 4840 3872]]
substraction [[-96 -43 -33]
 [-22  33  44]]
division [[0.03030303 0.44155844 0.625     ]
 [0.75       1.6        2.        ]]
modulus [[ 3 34 55]
 [66 33  0]]


In [43]:
#scalar operation 
a=np.arange(1,12)
print(a)
print("addition",a+3)
print("multiplication",a*2)
print("substraction",a-5)
print("division",a/4)
print("modulus",a%10)

[ 1  2  3  4  5  6  7  8  9 10 11]
addition [ 4  5  6  7  8  9 10 11 12 13 14]
multiplication [ 2  4  6  8 10 12 14 16 18 20 22]
substraction [-4 -3 -2 -1  0  1  2  3  4  5  6]
division [0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75]
modulus [1 2 3 4 5 6 7 8 9 0 1]


In [47]:
#copy and view

#copy
a=np.array([2,3,4,5,6])
b=a.copy()
print(a)
print(b)
b[1]=101
print(b)
print(a)

[2 3 4 5 6]
[2 3 4 5 6]
[  2 101   4   5   6]
[2 3 4 5 6]


In [54]:
#view
a=np.array([2,3,4,5,6])
b=a.view()
print(a)
print(b)
b[3]=400
print(b)
print(a)

[2 3 4 5 6]
[2 3 4 5 6]
[  2   3   4 400   6]
[  2   3   4 400   6]


In [53]:
#logical operator and condition
a=np.array([2,3,4,5,6])
print(a>5)
print(a[a>5])

[False False False False  True]
[6]


In [62]:
#print values between 2 and 5
print(a[(a>=2)&(a<=5)])

[2 3 4]


In [66]:
#reshaping is method of converting one dimensional to other dimensional
x=np.arange(1,13)
print(x)
print("dim",x.ndim)

y=x.reshape(3,4)
print(y)
print("dim",y.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
dim 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dim 2


In [75]:
x=np.arange(1,121)
print(x)

y=x.reshape(4,-1)
print(y)

z=x.reshape(-1,10)
print(z)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120]
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48
   49  50  51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80  81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
  109 110 111 112 113 114 115 116 117 118 119 120]]
[[  1   2  

In [86]:
#reshaping 2D to 1D
#flatten()- creates copy of original values
#ravel()- creates view of original values
a=np.array([[2,3,4],[6,7,8],[4,5,6],[8,9,8]])
print(a)
print("dim",a.ndim)
#flatten
b=a.flatten()
print(b)
print("dim",b.ndim)
b[1]=100
print(b)
print(a)


[[2 3 4]
 [6 7 8]
 [4 5 6]
 [8 9 8]]
dim 2
[2 3 4 6 7 8 4 5 6 8 9 8]
dim 1
[  2 100   4   6   7   8   4   5   6   8   9   8]
[[2 3 4]
 [6 7 8]
 [4 5 6]
 [8 9 8]]


In [85]:
#ravel
c=a.ravel()
print(c)
print("dim:",c.ndim)

c[1]=100
print(c)
print(a)

[  2 100   4   6   7   8   4   5   6   8   9   8]
dim: 1
[  2 100   4   6   7   8   4   5   6   8   9   8]
[[  2 100   4]
 [  6   7   8]
 [  4   5   6]
 [  8   9   8]]


In [11]:
#task-create 2 3D arrays and use flatten() and ravel() method for both and check dimensions
import numpy as np  
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("adim",a.ndim)
print("bdim",b.ndim )
c=a.flatten()
print(c)
d=b.flatten()
print(d)
print("dim",c.ndim)
print("dim",d.ndim)
e=a.ravel()
f=b.ravel()
print(e)
print(f)
print("dim",e.ndim)
print("dim",f.ndim)

adim 3
bdim 3
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
dim 1
dim 1
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
dim 1
dim 1


In [37]:
#task-create 1D array with 54 values,reshape to 5 different 2D arrays
a=np.arange(1,55)
print(a)
b=a.reshape(3,-1)
print(b)
c=a.reshape(-1,3)
print(c)
d=a.reshape(6,-1)
print(d)
e=a.reshape(-1,6)
print(e)
f=a.reshape(1,-1)
print(f)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
